# Generated by Django 5.1.4 on 2025-09-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0001_initial'),
    ]

    operations = [
    ]
